--NUEVAS TECNOLOGÍAS

CONECTAR GITHUB

CONECTAR CODEX (CHATGPT) 

CONECTAR COPILOT
https://ai.azure.com/


CREAR UNA SUBSCRIPCION
CREAR UN RECURSO
AZURE AI FOUNDRY -> CREAR UN MODELO


DOCUMENTACIÓN (NOTION + NOTION AI)

--BUENAS PRACTICAS (JUNIOR -> SENIOR)

1. COMENTANDO EL CODIGO, BLOQUE POR BLOQUE
2. PUEDO EJECUTARLO VARIAS VECES ("RELANZARLO") EN LA MISMA VENTANA
3. PENSAR A FUTURO
4. PLANIFICAR MEJORAS, O CORREGIR DEUDA TECNICA