--CONSULTA TOP 10 CLIENTES QUE MÁS COMPRARON EN 2023
SELECT TOP 10 ClienteId, SUM(Monto) AS TotalGastado
FROM Ventas
WHERE YEAR(FechaVenta) = 2023
GROUP BY ClienteId
ORDER BY TotalGastado DESC;

--CREAR/ACTUALIZAR VISTA CON LOS TOP 5 PRODUCTOS CON MÁS VENTAS
CREATE OR ALTER VIEW VW_TOP5_PRODUCTOS AS
SELECT TOP 5 ProductoId, SUM(Monto) AS TotalVendido
FROM Ventas
GROUP BY ProductoId
ORDER BY TotalVendido DESC;
